channels:
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.8.11
  - nodejs=14.8.0
  - pip:
    - jupyterlab==3.0.16
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - numpy==1.19.5
    - scipy==1.5.0
    - numba==0.52.0
    - runipy==0.1.5
    - jupyter_contrib_nbextensions==0.5.1
    - jupyter_nbextensions_configurator==0.4.1
